# -*- restclient -*-

:host = ml9ea4
:db   = foo-content

# retrieve DB properties
GET http://:host:8002/manage/v2/databases/:db/properties
Accept: application/json

# retrieve AS properties
GET http://:host:8002/manage/v2/servers/simple-dog/properties?group-id=Default
Accept: application/json

# save document
PUT http://:host:8000/v1/documents?uri=/test/doc.json&database=:db
Content-Type: application/json

{ "hello": "World!" }

# retrieve the saved document
GET http://:host:8000/v1/documents?uri=/test/doc.json&database=:db
